# webscraper/meyer/supabase_uploader.py

import os
import json
from datetime import datetime
from typing import Dict, List, Optional

from dotenv import load_dotenv
from supabase import create_client, Client
import logging

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class MeyerSupabaseUploader:
    def __init__(self, supabase_url: str = None, supabase_key: str = None):
        """
        Initialize the Meyer Supabase uploader.

        Args:
            supabase_url: Supabase project URL
            supabase_key: Supabase anon/service key
        """

        load_dotenv()
        self.supabase_url = supabase_url or os.environ.get("SUPABASE_URL")
        self.supabase_key = supabase_key or os.environ.get("SUPABASE_KEY")

        if not self.supabase_url or not self.supabase_key:
            raise ValueError("Supabase URL and key must be provided or set in environment variables")

        self.client: Client = create_client(self.supabase_url, self.supabase_key)
        self._hatchery_id = None

    @property
    def hatchery_id(self):
        """Get or fetch the Meyer hatchery ID"""
        if not self._hatchery_id:
            result = self.client.table('hatcheries').select('id').eq('code', 'meyer').single().execute()
            self._hatchery_id = result.data['id']
        return self._hatchery_id

    def upload_product(self, product_data: Dict) -> Dict:
        """
        Upload a Meyer product to Supabase.

        Args:
            product_data: Dictionary containing the Ecwid product data

        Returns:
            Dictionary with the created product record
        """
        try:
            # First, try to find or create a breed alias
            breed_alias_id = self._get_or_create_breed_alias(product_data['name'])

            # Extract categories
            category_ids = [cat['id'] for cat in product_data.get('categories', [])]

            # Prepare product data
            meyer_product = {
                'breed_alias_id': breed_alias_id,
                'ecwid_product_id': product_data['id'],
                'meyer_sku': product_data.get('sku'),
                'product_url': product_data.get('url', ''),
                'product_slug': product_data.get('customSlug', product_data.get('autogeneratedSlug')),
                'product_name': product_data['name'],
                'description': product_data.get('description', ''),
                'seo_title': product_data.get('seoTitle', ''),
                'seo_description': product_data.get('seoDescription', ''),
                'attributes': product_data.get('attributes', []),
                'category_ids': category_ids,
                'default_category_id': product_data.get('defaultCategoryId'),
                'main_image_url': product_data.get('imageUrl', ''),
                'gallery_images': product_data.get('galleryImages', []),
                'is_shipping_required': product_data.get('isShippingRequired', True),
                'tax_class_code': product_data.get('tax', {}).get('taxClassCode'),
                'ecwid_created_at': self._parse_timestamp(product_data.get('created')),
                'ecwid_updated_at': self._parse_timestamp(product_data.get('updated')),
                'last_scraped_at': datetime.utcnow().isoformat()
            }

            # Upsert the product
            result = self.client.table('meyer_products').upsert(
                meyer_product,
                on_conflict='ecwid_product_id'
            ).execute()

            product_id = result.data[0]['id']

            # Upload pricing combinations
            self._upload_pricing_combinations(product_id, product_data)

            # Upload categories
            self._upload_categories(product_data.get('categories', []))

            # Link product to categories
            self._link_product_categories(product_id, category_ids)

            logger.info(f"Successfully uploaded product: {product_data['name']}")
            return result.data[0]

        except Exception as e:
            logger.error(f"Error uploading product {product_data.get('name', 'Unknown')}: {str(e)}")
            raise

    def _get_or_create_breed_alias(self, product_name: str) -> str:
        """
        Get or create a breed alias for the product.

        Args:
            product_name: The Meyer product name

        Returns:
            UUID of the breed_alias record
        """
        # Clean the product name
        clean_name = self._clean_breed_name(product_name)

        # Check if alias already exists
        existing = self.client.table('breed_aliases').select('id').eq(
            'hatchery_id', self.hatchery_id
        ).eq('hatchery_breed_name', product_name).execute()

        if existing.data:
            return existing.data[0]['id']

        # Try to find a matching breed using pattern matching
        breed_id = self._find_matching_breed(clean_name)

        # Create new breed alias
        new_alias = {
            'hatchery_id': self.hatchery_id,
            'hatchery_breed_name': product_name,
            'breed_id': breed_id,  # Will be None if no match found
            'mapping_method': 'pattern-match' if breed_id else 'unmatched',
            'mapping_confidence': 0.8 if breed_id else 0.0,
            'mapping_notes': f"Auto-matched from Meyer scraper for: {clean_name}"
        }

        # Use upsert instead of insert to handle potential duplicates
        result = self.client.table('breed_aliases').upsert(
            new_alias,
            on_conflict='hatchery_id,hatchery_breed_name'
        ).execute()
        return result.data[0]['id']

    def _clean_breed_name(self, name: str) -> str:
        """Clean breed name for matching"""
        # Remove common suffixes
        suffixes = ['Day Old Chicks', 'Chicks', 'Chickens', 'Pullets', 'Cockerels']
        for suffix in suffixes:
            name = name.replace(suffix, '')

        # Remove extra whitespace
        return ' '.join(name.split()).strip()

    def _find_matching_breed(self, clean_name: str) -> Optional[str]:
        """
        Try to find a matching breed in the breeds table.

        Args:
            clean_name: Cleaned breed name

        Returns:
            UUID of matching breed or None
        """
        # Try exact match first
        result = self.client.table('breeds').select('id').eq(
            'standard_name', clean_name
        ).execute()

        if result.data:
            return result.data[0]['id']

        # Try case-insensitive match
        result = self.client.table('breeds').select('id').ilike(
            'standard_name', clean_name
        ).execute()

        if result.data:
            return result.data[0]['id']

        # Try partial match for common breed names
        # This is a simplified version - you might want more sophisticated matching
        words = clean_name.lower().split()
        if len(words) >= 2:
            # Try first two words
            partial_name = ' '.join(words[:2])
            result = self.client.table('breeds').select('id').ilike(
                'standard_name', f'%{partial_name}%'
            ).execute()

            if result.data and len(result.data) == 1:
                return result.data[0]['id']

        return None

    def _upload_pricing_combinations(self, product_id: str, product_data: Dict):
        """Upload pricing combinations for a product"""
        combinations = product_data.get('combinations', [])

        for combo in combinations:
            # Extract gender from options
            gender_option = next(
                (opt for opt in combo.get('options', []) if opt['name'] == 'Gender'),
                None
            )

            if not gender_option:
                continue

            pricing_data = {
                'meyer_product_id': product_id,
                'ecwid_combination_id': combo['id'],
                'combination_number': combo.get('combinationNumber'),
                'sku': combo.get('sku'),
                'gender': gender_option['value'],
                'price': combo.get('price', 0),
                'displayed_price': combo.get('defaultDisplayedPrice'),
                'quantity': combo.get('quantity', 0),
                'unlimited': combo.get('unlimited', False),
                'in_stock': combo.get('inStock', True),
                'image_url': combo.get('imageUrl'),
                'thumbnail_url': combo.get('thumbnailUrl')
            }

            self.client.table('meyer_pricing_combinations').upsert(
                pricing_data,
                on_conflict='ecwid_combination_id'
            ).execute()

    def _upload_categories(self, categories: List[Dict]):
        """Upload categories to the database"""
        for category in categories:
            cat_data = {
                'id': category['id'],
                'name': category['name'],
                'name_translated': category.get('nameTranslated', {}),
                'enabled': category.get('enabled', True)
            }

            self.client.table('meyer_categories').upsert(
                cat_data,
                on_conflict='id'
            ).execute()

    def _link_product_categories(self, product_id: str, category_ids: List[int]):
        """Link product to categories"""
        # Get existing category links
        existing_links = self.client.table('meyer_product_categories').select('category_id').eq(
            'meyer_product_id', product_id
        ).execute()

        existing_category_ids = [link['category_id'] for link in existing_links.data] if existing_links.data else []

        # Categories to add (those in category_ids but not in existing_category_ids)
        categories_to_add = [cat_id for cat_id in category_ids if cat_id not in existing_category_ids]

        # Categories to remove (those in existing_category_ids but not in category_ids)
        categories_to_remove = [cat_id for cat_id in existing_category_ids if cat_id not in category_ids]

        # Remove categories that are no longer associated
        if categories_to_remove:
            for cat_id in categories_to_remove:
                self.client.table('meyer_product_categories').delete().eq(
                    'meyer_product_id', product_id
                ).eq('category_id', cat_id).execute()

        # Add new category links using upsert
        for cat_id in categories_to_add:
            self.client.table('meyer_product_categories').upsert({
                'meyer_product_id': product_id,
                'category_id': cat_id
            }, on_conflict='meyer_product_id,category_id').execute()

    def _parse_timestamp(self, timestamp_str: str) -> Optional[str]:
        """Parse Ecwid timestamp string to ISO format"""
        if not timestamp_str:
            return None

        try:
            # Parse format like "2020-06-29 20:10:35 +0000"
            dt = datetime.strptime(timestamp_str, "%Y-%m-%d %H:%M:%S %z")
            return dt.isoformat()
        except ValueError:
            logger.warning(f"Could not parse timestamp: {timestamp_str}")
            return None

    def batch_upload_products(self, products: List[Dict]) -> Dict:
        """
        Upload multiple products in batch.

        Args:
            products: List of product dictionaries

        Returns:
            Dictionary with upload statistics
        """
        stats = {
            'total': len(products),
            'successful': 0,
            'failed': 0,
            'errors': []
        }

        for product in products:
            try:
                self.upload_product(product)
                stats['successful'] += 1
            except Exception as e:
                stats['failed'] += 1
                stats['errors'].append({
                    'product': product.get('name', 'Unknown'),
                    'error': str(e)
                })

        logger.info(f"Batch upload complete: {stats['successful']} successful, {stats['failed']} failed")
        return stats


# Example usage function
def upload_meyer_data_to_supabase(product_data: Dict):
    """
    Convenience function to upload Meyer data to Supabase.

    Args:
        product_data: Dictionary containing the Ecwid product data
    """
    uploader = MeyerSupabaseUploader()
    return uploader.upload_product(product_data)


if __name__ == "__main__":
    # Example usage with the sample data
    sample_data = {
        # Your sample data here
    }

    # Initialize uploader
    uploader = MeyerSupabaseUploader()

    # Upload single product
    # result = uploader.upload_product(sample_data)
    # print(f"Uploaded product: {result}")
